#!/bin/bash

# Încearcă activarea venv-ului local
. .venv/bin/activate

# Dacă eșuează, încearcă fallback (activare pentru Jenkins)
if [ $? -eq 0 ]
then
    echo "SUCCESS: venv was activated."
else
    echo "FAIL: cannot activate venv"
    . ./activeaza_venv_jenkins
fi
